// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Shared = require("./Shared.bs.js");
var ReactNativeGestureHandler = require("react-native-gesture-handler");

var TapGestureHandler = /* module */[];

function make(minPointers, maxDurationMs, maxDelayMs, numberOfTaps, maxDeltaX, maxDeltaY, maxDist, enabled, shouldCancelWhenOutside, simultaneousHandlers, waitFor, hitSlop, onGestureEvent, onHandlerStateChange) {
  return ReactNativeGestureHandler.TapGestureHandler(minPointers, maxDurationMs, maxDelayMs, numberOfTaps, maxDeltaX, maxDeltaY, maxDist, enabled, shouldCancelWhenOutside, simultaneousHandlers, waitFor, Shared.hitSlopToJs(hitSlop), onGestureEvent, onHandlerStateChange);
}

exports.TapGestureHandler = TapGestureHandler;
exports.make = make;
/* react-native-gesture-handler Not a pure module */
