// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Shared = require("./Shared.bs.js");
var ReactNativeGestureHandler = require("react-native-gesture-handler");

var PanGestureHandler = /* module */[];

function make(minDist, minPointers, maxPointers, activeOffsetX, activeOffsetY, failOffsetY, failOffsetX, avgTouches, enabled, shouldCancelWhenOutside, simultaneousHandlers, waitFor, hitSlop, onGestureEvent, onHandlerStateChange) {
  return ReactNativeGestureHandler.PanGestureHandler(minDist, minPointers, maxPointers, activeOffsetX, activeOffsetY, failOffsetY, failOffsetX, avgTouches, enabled, shouldCancelWhenOutside, simultaneousHandlers, waitFor, Shared.hitSlopToJs(hitSlop), onGestureEvent, onHandlerStateChange);
}

exports.PanGestureHandler = PanGestureHandler;
exports.make = make;
/* react-native-gesture-handler Not a pure module */
