// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNativeGestureHandler = require("react-native-gesture-handler");

var PinchGestureHandler = /* module */[];

function make(prim, prim$1) {
  return ReactNativeGestureHandler.PinchGestureHandler(prim !== undefined ? Caml_option.valFromOption(prim) : undefined, prim$1 !== undefined ? Caml_option.valFromOption(prim$1) : undefined);
}

exports.PinchGestureHandler = PinchGestureHandler;
exports.make = make;
/* react-native-gesture-handler Not a pure module */
