// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNativeGestureHandler = require("react-native-gesture-handler");

var Direction = /* module */[];

var FlingGestureHandler = /* module */[];

function make(prim, prim$1, prim$2, prim$3, prim$4, prim$5, prim$6, prim$7, prim$8) {
  return ReactNativeGestureHandler.FlingGestureHandler(prim !== undefined ? Caml_option.valFromOption(prim) : undefined, prim$1 !== undefined ? Caml_option.valFromOption(prim$1) : undefined, prim$2 !== undefined ? Caml_option.valFromOption(prim$2) : undefined, prim$3 !== undefined ? Caml_option.valFromOption(prim$3) : undefined, prim$4 !== undefined ? Caml_option.valFromOption(prim$4) : undefined, prim$5 !== undefined ? Caml_option.valFromOption(prim$5) : undefined, prim$6 !== undefined ? Caml_option.valFromOption(prim$6) : undefined, prim$7 !== undefined ? Caml_option.valFromOption(prim$7) : undefined, prim$8 !== undefined ? Caml_option.valFromOption(prim$8) : undefined);
}

exports.Direction = Direction;
exports.FlingGestureHandler = FlingGestureHandler;
exports.make = make;
/* react-native-gesture-handler Not a pure module */
